name: blog_of_aimmetal
description: A documentation site built with Jaspr
version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  jaspr: ^0.22.0
  jaspr_content: ^0.4.2
  jaspr_router: ^0.8.1

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_builder: ^0.22.0
  jaspr_lints: ^0.6.0
  jaspr_web_compilers: ^4.2.3+1
  lints: ^6.0.0

jaspr:
  mode: static
